name: Schedule Job

on:

schedule:
    -cron: "0 0 * * *"

jobs:
   run-script:
       runs-on: ubantu-latest

      steps:
          -name: Print Message
           run: echo "Schedule  workflow executed"
